target_labels = ['Help Wanted',
                 '🙋🏻\u200d♂️help wanted',
                 'E-starter',
                 'type: help wanted :slightly_smiling_face:',
                 'difficulty:beginner',
                 ':fire: good first issue',
                 '🌳 help wanted',
                 'issue: help wanted',
                 'help wanted:paper implementation',
                 'info: help wanted',
                 'starter',
                 'help wanted (easy)',
                 'Help needed',
                 'help wanted/question',
                 'help wanted',
                 'contrib: help needed',
                 'X5: work required (PR / Help Wanted)',
                 'Help Wanted-Good first issue',
                 'Starter',
                 'Help wanted',
                 'good first issue :1st_place_medal:',
                 '👋 good first issue',
                 'type::beginner',
                 'Contribution::Help Wanted',
                 'Status: Help Wanted',
                 'good-beginner-bug',
                 'status: good first issue',
                 ':smiling_imp: good first issue',
                 'Good first issue',
                 '🙏help wanted',
                 'Level:Starter',
                 'good first issue :baby_chick:',
                 'good first issue 👍',
                 ':bulb: Help wanted',
                 'Status: Community help needed',
                 'help wanted/suggest',
                 'difficulty: beginner',
                 'contrib: good first issue',
                 'for beginners',
                 'module/seata-spring-boot-starter',
                 'status: help wanted',
                 'Good for beginner contribution',
                 'Good first issue!',
                 'code help wanted',
                 'disposition/good first issue',
                 'Type: Help wanted',
                 'Beginner friendly',
                 'help wanted :sos:',
                 'beginner-friendly',
                 'help needed',
                 'info: good first issue',
                 'question & help wanted',
                 'good first Issue',
                 'Beginner Friendly',
                 'community help wanted',
                 ':fire: help wanted',
                 'community/help wanted',
                 'Difficulty - Beginner',
                 'disposition/help wanted',
                 'beginner-task',
                 'Help Wanted :octocat:',
                 'Help Needed',
                 'beginner friendly',
                 'good first issue',
                 'state: help needed',
                 'Difficulty: starter',
                 '🙇\u200d♂️ help wanted',
                 '✅ good first issue',
                 'fit for beginners',
                 'difficulty: starter',
                 ':gift: BEGINNER',
                 'good first issue candidate',
                 'good first issue (taken)',
                 'exp/beginner',
                 'starter-task',
                 'Type: Help Needed',
                 'beginner',
                 'Starter bug',
                 'Good First Issue',
                 'community/good first issue']
